# Generated by Django 4.2.5 on 2023-09-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_collar_qr_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collar',
            name='img_url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
