export const COLLAR_VIEW = 'COLLAR_VIEW';
export const UPDATE_COLLAR_VIEW = 'UPDATE_COLLAR_VIEW';
export const CREATE_COLLAR_VIEW = 'CREATE_COLLAR_VIEW';
export const SCAN_QR_VIEW = 'SCAN_QR_VIEW';
export const HOME_VIEW = 'HOME_VIEW';
